name: dist-package dry-run (binary artifacts)

permissions:
  contents: read

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  dist-package-dry-run:
    name: ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-pc-windows-msvc
            os: windows-2025
          - target: aarch64-apple-darwin
            os: macos-15
    continue-on-error: true
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Setup environment for MSVC"
        # mirrors .cargo/config.toml [target.x86_64-pc-windows-msvc] rustflags
        shell: bash
        run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static -C link-arg=/STACK:8388608" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')

      - name: "Setup environment for aarch64-darwin"
        # lux-lua needs this to build on darwin
        run: echo "RUSTFLAGS=${RUSTFLAGS} -C link-arg=-undefined -C link-arg=dynamic_lookup" >> "${GITHUB_ENV}"
        if: startsWith(matrix.target, 'aarch64-apple-darwin')

      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
        if: "startsWith(matrix.os, 'windows')"

      - name: Install build dependencies (Linux)
        if: "startsWith(matrix.os, 'ubuntu')"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgpgme11-dev \
            libgpg-error-dev \

      - name: Install build dependencies (macOS)
        if: "startsWith(matrix.os, 'macos')"
        run: brew install gpgme

      - name: Build binary distributions (*nix)
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          cargo xtask dist-package-dry-run
        env:
          SYSTEM_DEPS_LINK: static
          LUX_SIGN_PRIVATE_KEY: ${{ secrets.LUX_SIGN_PRIVATE_KEY }}
          LUX_SIGN_PRIVATE_KEY_PASS: ${{ secrets.LUX_SIGN_PRIVATE_KEY_PASS }}

      - name: Build binary distributions (Windows)
        if: "startsWith(matrix.os, 'windows')"
        run: |
          cargo xtask dist-package-dry-run
        env:
          SYSTEM_DEPS_LINK: static
          LUX_SIGN_PRIVATE_KEY: ${{ secrets.LUX_SIGN_PRIVATE_KEY }}
          LUX_SIGN_PRIVATE_KEY_PASS: ${{ secrets.LUX_SIGN_PRIVATE_KEY_PASS }}

